"""Shared types and constants for claims validation rules."""

from __future__ import annotations

from typing import Any

VALIDATION_NEGATIVE_AMOUNT = "VALIDATION_NEGATIVE_AMOUNT"
VALIDATION_INVALID_DATE_ORDER = "VALIDATION_INVALID_DATE_ORDER"
NOT_FOUND_PATIENT = "NOT_FOUND_PATIENT"
NOT_FOUND_PROVIDER = "NOT_FOUND_PROVIDER"
CONFLICT_DUPLICATE_CLAIM_ID = "CONFLICT_DUPLICATE_CLAIM_ID"

Violation = dict[str, Any]
